enum employeeType {
    GET_ALL_USER_START='GET_ALL_USER_START',
    GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_ERROR = 'GET_ALL_USER_ERROR',
    DELETE_EMPLOYEE_START='DELETE_EMPLOYEE_START',
    DELETE_EMPLOYEE_SUCCESS='DELETE_EMPLOYEE_SUCCESS',
    DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR',
    RESET_DELETE_EMPLOYEE_STATE = 'RESET_DELETE_EMPLOYEE_STATE',
    ADD_EMPLOYEE_START='ADD_EMPLOYEE_START',
    ADD_EMPLOYEE_SUCCESS='ADD_EMPLOYEE_SUCCESS',
    ADD_EMPLOYEE_ERROR='ADD_EMPLOYEE_ERROR',
    RESET_ADD_EMPLOYEE_STATE='RESET_ADD_EMPLOYEE_STATE',
    GET_EMPLOYEE_BY_ID_START='GET_EMPLOYEE_BY_ID_START',
    GET_EMPLOYEE_BY_ID_SUCCESS='GET_EMPLOYEE_BY_ID_SUCCESS',
    GET_EMPLOYEE_BY_ID_ERROR='GET_EMPLOYEE_BY_ID_ERROR',
    RESET_GET_EMPLOYEE_BY_ID_STATE='RESET_GET_EMPLOYEE_BY_ID_STATE',
    GET_COUNTRY_DETAILS_SUCCESS='GET_COUNTRY_DETAILS_SUCCESS',
    GET_COUNTRY_DETAILS_ERROR='GET_COUNTRY_DETAILS_ERROR',
    GET_BANK_DETAILS_SUCCESS='GET_BANK_DETAILS_SUCCESS',
    GET_BANK_DETAILS_ERROR='GET_BANK_DETAILS_ERROR'
  }

  export default employeeType;